import type { Metadata } from "next";
import { Inter as FornSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/shared/ui/utils";
import { Toaster } from "@/shared/ui/sonner";

const fontSans = FornSans({
    subsets: ["cyrillic", "latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased",
                    fontSans.variable,
                )}
            >
                {children}
                <Toaster />
            </body>
        </html>
    );
}
